### ISSUE TITLE
rand crate discussion 

### ISSUE THREAD

**Issue by nothingismagick** [Alex6323/bee-p#17]
https://github.com/Alex6323/bee-p/blob/a3b54b899efd017a1f0ed5141ea1a271475bb740/bee-signing/Cargo.toml#L12

I would like to propose considering using the `randomize` crate instead. What I like about it is that we can attach a hardware generator if available. It comes recommended from the Tauri core team.

https://docs.rs/randomize/3.0.1/randomize/

**Comment by thibault-martinez** [comment]
What about the big `NOT FOR CRYPTOGRAPHIC PURPOSES.` on their homepage ?

**Comment by nothingismagick** [comment]
I somehow always manage to overlook text that screams at me.
