### ISSUE TITLE
panicked at 'Error while confirming milestone, aborting.'

### ISSUE THREAD

**Issue by rufsam** [Alex6323/bee-p#218]
[2020-08-31][22:48:00][bee_protocol::worker::status][[92mINFO[0m] Synchronizing 1643070..1643748..1643749 (99%) - Requested 0.
[2020-08-31][22:48:01][bee_node::plugin::tps][[92mINFO[0m] incoming 11 new 11 known 0 stale 0 invalid 0 outgoing 0
[2020-08-31][22:48:02][bee_node::plugin::tps][[92mINFO[0m] incoming 15 new 15 known 0 stale 0 invalid 0 outgoing 0
[2020-08-31][22:48:02][bee_ledger::whiteflag::worker][[91mERROR[0m] Tried to confirm 1643750 on top of 1643748.
thread 'async-std/runtime' panicked at 'Error while confirming milestone, aborting.', bee-ledger/src/whiteflag/worker.rs:172:25

**Comment by luca-marchiori** [comment]
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:42][bee_node::plugin::tps][[92mINFO[0m] incoming 2 new 2 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:41][bee_node::plugin::tps][[92mINFO[0m] incoming 10 new 10 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  27:                0x0 - <unknown>
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  26:     0x7f646fe8d103 - __clone
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  25:     0x7f646ff81609 - start_thread
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/sys/unix/thread.rs:87
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  24:     0x559996618bea - std::sys::unix::thread::Thread::new::thread_start::h276e6ca033938925
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  23:     0x559996618bea - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1044417e186e567a
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  22:     0x559996618bea - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hd2b3bc04af94a84f
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  21:     0x559996561502 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc304a13d010c4ee0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  20:     0x5599965639f6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h155d1be23cbc14db
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  19:     0x559996564217 - async_global_executor::init_with_config::{{closure}}::hf790db724e4c7096
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  18:     0x559996564755 - async_io::reactor::Reactor::block_on::h25d37d9aa5ea19ea
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  17:     0x559996564101 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hec3c02c45a910b21
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  16:     0x559996563fd0 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc283edfbee16f4e2
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  15:     0x5599964cefa1 - async_task::raw::RawTask<F,T,S>::run::haaee9366348affb9
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  14:     0x5599964d537b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6d5f6ae947ac736f
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  13:     0x5599964cb8dc - std::thread::local::LocalKey<T>::with::hb6dacdc7c21a26d7
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  12:     0x5599964d51ba - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h4c089fd14566f546
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  11:     0x5599964ce87e - std::panicking::begin_panic::h1693081e2d323ba4
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/panicking.rs:526
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP  10:     0x559996615e33 - std::panicking::rust_panic_with_hook::he82f5d0644692441
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/panicking.rs:217
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   9:     0x55999661553c - std::panicking::default_hook::hecc34e3f729e213c
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/panicking.rs:198
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   8:     0x5599966157f0 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/sys_common/backtrace.rs:49
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   7:     0x5599966157f0 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/sys_common/backtrace.rs:62
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   6:     0x5599966157f0 - std::sys_common::backtrace::_print::hfc0110703f3696fd
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/io/mod.rs:1537
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   5:     0x55999660c362 - std::io::Write::write_fmt::hf3afc6cfd57d0033
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libcore/fmt/mod.rs:1076
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   4:     0x55999663963c - core::fmt::write::he0c1e5f7426d2718
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/sys_common/backtrace.rs:59
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   3:     0x559996613135 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at src/libstd/sys_common/backtrace.rs:78
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   2:     0x559996613135 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   1:     0x559996613135 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP   0:     0x559996613135 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP stack backtrace:
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP thread 'async-std/runtime' panicked at 'Error while confirming milestone, aborting.', bee-ledger/src/whiteflag/worker.rs:72:25
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:40][bee_ledger::whiteflag::worker][[91mERROR[0m] Tried to confirm 1830997 on top of 1830995.
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:40][bee_protocol::protocol::protocol][[92mINFO[0m] New milestone 1830997 RZQFOIVDEKFVFMJPITERXUWJOYGVJLBL9ZZGYURYIIBTWATSBHDQTEG9I9AQPPBRUDBEQRAYXPSBZ9999.
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:40][bee_node::plugin::tps][[92mINFO[0m] incoming 11 new 11 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:39][bee_node::plugin::tps][[92mINFO[0m] incoming 5 new 5 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:38][bee_node::plugin::tps][[92mINFO[0m] incoming 8 new 8 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:37][bee_node::plugin::tps][[92mINFO[0m] incoming 7 new 7 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:37][bee_protocol::worker::status][[92mINFO[0m] Synchronizing 1830852..1830995..1830996 (99%) - Requested 0.
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:36][bee_node::plugin::tps][[92mINFO[0m] incoming 6 new 6 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:35][bee_node::plugin::tps][[92mINFO[0m] incoming 3 new 3 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:34][bee_node::plugin::tps][[92mINFO[0m] incoming 9 new 9 known 0 stale 0 invalid 0 outgoing 0
Sep 22 07:40:43 192.168.1.81 Sep 22 07:40:43 bee APP [2020-09-22][07:40:33][bee_node::plugin::tps][[92mINFO[0m] incoming 7 new 7 known 0 stale 0 invalid 0 outgoing 0
