### ISSUE TITLE
bee-ternary package needs to be specified explicitly

### ISSUE THREAD

**Issue by CMIT-RomanP** [Alex6323/bee-p#290]
Please correct bee-ternary dependencies, should be "bee-ternary = { version = "0.3.2-alpha", git = "https://github.com/iotaledger/bee.git", branch = "dev", features = ["serde1"] }".

**Comment by thibault-martinez** [comment]
Hi, out of curiosity, what kind of issue are you having with it not being explicit ? And why bee-ternary specifically ?

**Comment by CMIT-RomanP** [comment]
I am working on a program using IOTA Streams and I am not able to translate. This is the result of a cargo build

Updating crates.io index
Updating git repository `https://github.com/iotaledger/iota.rs`
Updating git repository `https://github.com/iotaledger/iota.rs`
Updating git repository `https://github.com/iotaledger/streams`
Updating git repository `https://github.com/iotaledger/bee.git`
Updating git repository `https://github.com/Alex6323/bee-p.git`
error: no matching package named `bee-ternary` found
location searched: https://github.com/iotaledger/bee.git?branch=dev
prerelease package needs to be specified explicitly
bee-ternary = { version = "0.3.2-alpha" }
required by package `iota-core v0.2.0-alpha.3 (https://github.com/iotaledger/iota.rs?rev=0ad8e7f#0ad8e7f7)`

**Comment by thibault-martinez** [comment]
Can you try `cargo update` then `cargo build` please ?
